### ISSUE TITLE
Export initializers given a pre-existing netbox install

### ISSUE THREAD

**Issue by ryanmerolle** [tobiasge/netbox-initializers#33]
### Proposed functionality

It would be interesting to use an existing netbox install with existing data to export to yaml.

### Use case

Allow for quick building of initializer data

**Comment by tobiasge** [comment]
Doesn't Netbox already offer an export into YAML?

**Comment by ryanmerolle** [comment]
Well if it does, I will look at documenting how to use with the initializers when I have a moment.

**Comment by cimnine** [comment]
See [`manage.py dumpdata`][dump] and [`manage.py loaddata`][load].

[dump]: https://docs.djangoproject.com/en/4.1/ref/django-admin/#dumpdata
[load]: https://docs.djangoproject.com/en/4.1/ref/django-admin/#loaddata
