### ISSUE TITLE
NetBox 3.5 Support

### ISSUE THREAD

**Issue by ryanmerolle** [tobiasge/netbox-initializers#43]
### Proposed functionality

Currently NetBox 3.5 will not run with this plugin installed.

Please see [the release notes for 3.5 changes](https://github.com/netbox-community/netbox/releases/tag/v3.5.0)

### Use case

NetBox 3.5 Support

**Comment by tobiasge** [comment]
https://github.com/tobiasge/netbox-initializers/releases/tag/v3.5.0
