### ISSUE TITLE
Plugin Support NetBox v3.3 

### ISSUE THREAD

**Issue by hpreston** [tobiasge/netbox-initializers#8]
### Proposed functionality

Now that NetBox v3.3 is available I was curious when this plug-in might be updated to support this latest version?  I haven't done any plug-in development myself yet so I don't know how complicated updating the plugin to the latest version of NetBox would be.  

Looking at the release notes for NetBox v3.3 I don't notice any breaking changes in the plugins support, so hopefully this could be as simple as just testing and updating the max version supported by the plugin.  

### Use case

Now that initializers are no longer part of netbox-docker, this plugin is required to support initializing instances of NetBox with data for development.

**Comment by tobiasge** [comment]
The is with the cable terminations  which were rewritten in Netbox 3.3.

**Comment by hpreston** [comment]
Ah yeah, that will at least change the example initializers and maybe how they are processed in.  

I've been poking at the plugin code as I'm working on my upgrade from 2.10 and found a couple things I'm thinking of opening a PR for to resolve.  While I'm in there I'll see if I can look at the cable initializer.  My setup includes interfaces and cables in the initializer data so I've got a data set to work with.  If I work out the updates needed for v3.3 I'll send in a PR for you to review.

**Comment by steffenschumacher** [comment]
I think we should have a latest or 'dev' version of this plugin, which doesn't set a max version - since its versioned differently it should be obvious that things could break, but it allows the user to try the plugin out with newer versions of netbox?

Its a bit weird to have to fork this, just to be able to spin this on 3.3?

**Comment by hpreston** [comment]
I'm starting to work on updating the plugin to support v3.3 and had a question on the design intentions for the plugin itself related to versions of the plugin and versions of NetBox.  

Should the major / minor numbers of the version tie to the version of NetBox directly for support specifically?  Or should versions of the plugin support older versions of NetBox as well?  

For example, would  `3.3.x` of the plugin support NetBox `3.3.x` only, but NOT necessarily support NetBox `3.2.x`?  Specifically related to the data models and changes between versions?  

Or does there need to be logic in the plugin to check the version of NetBox and adjust the logic to backwards support older versions of NetBox?  

I couldn't tell from the `Releases.md` file what was intended.  

While I like the idea of backwards support for older versions of NetBox, that will significantly add code to the plugin to handle the discovery of version and changes needed.  

Having plugin version tied to NetBox version has the downside of potentially needing to maintain multiple "releases" and back porting updates.. 

I did look at the Plugin Developers guide for NetBox and there doesn't seem to be any guidance at that level.  Because this plugin is so tightly coupled to the NetBox version and data models, it's probably not as big an issue for other plugins.

**Comment by tobiasge** [comment]
I was planing to tie the versions directly together. So version 3.3.x of the plugin should only support Netbox 3.3.y.
When the initializers were included in the Docker image we had the same compatibility. I think back-porting minor bug fixes to an older version isn't that big a problem.

I've already written something about a branching model I intend to use, but that's not committed yet. I will probably do that tomorrow.

**Comment by hpreston** [comment]
That sounds perfect @tobiasge .  I'm working through the changes to the cable model now against my lab setup for v3.3.  

I'm looking at how to keep the YAML file format the same as in v3.2 but process it with the changes and addition of "CableTerminations" in v3.3.  So far it looks like it'll work.  I'm hoping to have a functional prototype working by end of the day, and it ready to send over for a review tomorrow.

**Comment by tobiasge** [comment]
@hpreston In #19 are some more docs about the development and release process. I hope they help in understanding.

**Comment by steffenschumacher** [comment]
> So version 3.3.x of the plugin should only support Netbox 3.3.y.
Again, I think it would be quite nice if we allowed for the latest version (eg. 3.3.x) to support future netbox versions (eg. >= 3.3.x) so that the the latest version will be installable even if its not fully compatible with some later version of NetBox.
Once the fixes are in, it can be capped to whichever version of netbox its compatible with, and a new version with the fixes will be installable in future versions.

**Comment by tobiasge** [comment]
Release for Netbox 3.3 support is published.

Closing here, because at the moment I don't like the idea of publishing releases that are not fully compatible with the Netbox version in which they could be installed. I think that will only upset users.
